{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"pythonUPVX20.ipynb","provenance":[],"collapsed_sections":[]},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"markdown","metadata":{"id":"LcllXzQOmlgc","colab_type":"text"},"source":["# Errores típicos de ejecución"]},{"cell_type":"code","metadata":{"id":"KWlupvbWmqpL","colab_type":"code","colab":{}},"source":["10/0"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"41aC-7afms4S","colab_type":"code","colab":{}},"source":["4 + spam*2"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"4Pu3Do-fmvlp","colab_type":"code","colab":{}},"source":["'2'+ 2"],"execution_count":0,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"1sCfVGYPmwjT","colab_type":"text"},"source":["además errores de archivo, conexión, comunicación, entrada de datos..."]},{"cell_type":"markdown","metadata":{"id":"mt80SWvrerLI","colab_type":"text"},"source":["# Manejando errores\n","\n","Supongamos que le pedimos al usuario que nos introduzca un número para hacer un cálculo pero..."]},{"cell_type":"code","metadata":{"id":"vp5sjAKDebTd","colab_type":"code","colab":{}},"source":["valor = input('Escribe el número:') #pero el usuario lo pone con letras\n","valor_numerico = int(valor)\n","resultado = valor_numerico + 3\n","print(resultado)"],"execution_count":0,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"HdfUHMlcfHsA","colab_type":"text"},"source":["El bloque try/except"]},{"cell_type":"code","metadata":{"id":"t0cthfSufg1u","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":51},"outputId":"3a6a717c-231a-450c-f4f5-9beae82dae65","executionInfo":{"status":"ok","timestamp":1576598012510,"user_tz":-60,"elapsed":1857,"user":{"displayName":"Leo Salom","photoUrl":"https://lh3.googleusercontent.com/a-/AAuE7mBWrU9A9PXLcaPaMIEPXT8vKmpShYH2PtLETEIgGQ=s64","userId":"07470075073569383292"}}},"source":["try:\n","  valor = input('Escribe el número:') #pero el usuario lo pone con letras\n","  valorNumerico = int(valor)\n","  resultado = valor_numerico + 3\n","  print(resultado)\n","except Exception as e:\n","    print('Hemos subrido un error debido a que:',str(e))"],"execution_count":19,"outputs":[{"output_type":"stream","text":["Escribe el número:tas\n","Hemos subrido un error debido a que invalid literal for int() with base 10: 'tas'\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"WpdbQp0JgD7g","colab_type":"text"},"source":["Esto resuelve nuestro problema si nuestro programa es así de sencillo pero que pasa cuando nuestra aplicación debe seguir realizando cosas con el contenido de la variable **valorNumerico** más adelante? "]},{"cell_type":"code","metadata":{"id":"1CV4yOs3gS3X","colab_type":"code","colab":{}},"source":["try:\n","  valor = input('Escribe el número:') #pero el usuario lo pone con letras\n","  valorNumerico = int(valor)\n","  resultado = valor_numerico + 3\n","  print(resultado)\n","except:\n","    valorNumerico = 0\n","\n","print(valorNumerico + 3)"],"execution_count":0,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"MyiOEjgtgm1H","colab_type":"text"},"source":["## Cuidado con los bloques try muy largos"]},{"cell_type":"code","metadata":{"id":"ry2ulOoCgxgG","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":34},"outputId":"4a87c7b3-c6f7-4162-9323-eeb6494a1271","executionInfo":{"status":"ok","timestamp":1576597469861,"user_tz":-60,"elapsed":628,"user":{"displayName":"Leo Salom","photoUrl":"https://lh3.googleusercontent.com/a-/AAuE7mBWrU9A9PXLcaPaMIEPXT8vKmpShYH2PtLETEIgGQ=s64","userId":"07470075073569383292"}}},"source":["try:\n","  valor = 'siete' \n","  valorNumerico = int(valor) \n","  resultado = valorNumerico + 3 #esto no se ejecutará porque falla en la linea anterior\n","  print(resultado)\n","except ValueError:\n","    valorNumerico = 0\n","\n","print(valorNumerico + 3)"],"execution_count":6,"outputs":[{"output_type":"stream","text":["3\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"Myt_kIRQkiZW","colab_type":"text"},"source":["Tipos de errores disponibles en la [documentación de python](https://docs.python.org/3/library/exceptions.html#Exception) y podemos actuar dependiendo del tipo de excepción.\n"]},{"cell_type":"code","metadata":{"id":"AP6IIt-Mkvks","colab_type":"code","colab":{}},"source":["try:\n","  valor = input('Introduce un valor :') \n","  valorNumerico = int(valor) #/0 #/dos\n","  resultado = valorNumerico + 3 \n","  print(resultado)\n","except ArithmeticError:\n","  print('Error aritmético')\n","except ValueError:\n","    valorNumerico = 0\n","except Exception as e:\n","   print('Hemos subrido un error debido a que:',str(e))\n","\n","print(valorNumerico + 3)"],"execution_count":0,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"Dh2TZWoShMMX","colab_type":"text"},"source":["## El grupo finally"]},{"cell_type":"code","metadata":{"id":"-qDlfkYJhpuz","colab_type":"code","colab":{}},"source":["try:\n","  valor = \"siete\"\n","  valorNumerico = int(valor) \n","  resultado = valorNumerico + 3 #esto no se ejecutará porque falla en la linea anterior\n","  print(resultado)\n","except ValueError:\n","    valorNumerico = 0\n","finally:\n","  print(valorNumerico + 3)"],"execution_count":0,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"POWZxfdxinM_","colab_type":"text"},"source":["Especialmente util para cerrar ficheros/conexiones a bases de datos/ sockets y básicamente el acceso a cualquier recurso bloqueante que pueda necesitar nuestra aplicación u otras aplicaciones."]}]}